name: Business Insight Engine CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ipykernel

      # Step 4: Download NLTK stopwords
      - name: Download NLTK resources
        run: |
          python -m nltk.downloader stopwords

      # Step 5: Create data folder
      - name: Create data folder
        run: mkdir -p data

      # Step 6: Run tests
      - name: Run CI tests
        run: |
          python -m pytest tests/test_ci.py
